swagger: '2.0'
info:
  title: IVC API
  description: IVC的REST接口
  version: 1.0.0
#host: 121.41.72.231:5001
host: 192.168.0.253:15001
#host: 192.168.1.150:9999
schemes:
  - http
basePath: /api/ivc/v1
produces:
  - application/json
paths:
  /{project_name}/cameras:
    get:
      summary: 获取摄像头列表
      tags: [Camera]
      parameters:
        - $ref: '#/parameters/project_name'
        - name: start
          in: query
          description: 返回的摄像头的起始索引
          required: false
          type: integer
          default: 0
        - name: limit
          in: query
          description: 最多返回的摄像头个数，最大100，最小0
          required: false
          type: integer
          default: 10
          maximum: 100
          minimum: 0
      responses:
        '200':
          description: 摄像头列表
          schema:
            type: object
            required:
              - total
              - start
            properties:
              total:
                type: integer
                description: 摄像头总数
              start:
                type: integer
                description: 摄像头的起始索引
              list:
                type: array
                description: 摄像头列表
                items:
                  - $ref: '#/definitions/camera'
  /{project_name}/cameras/{camera_id}:
    get:
      summary: 获取摄像头信息
      tags: [Camera]
      parameters:
        - $ref: '#/parameters/project_name'
        - $ref: '#/parameters/camera_id'
      responses:
        '200':
          description: 摄像头信息
          schema:
            $ref: '#/definitions/camera'
  /{project_name}/cameras/{camera_id}/sessions:
    post:
      summary: 请求观看媒体流
      description:
        客户端可通过该API获取指定摄像机的媒体流。
      tags: [User Session]
      parameters:
        - $ref: '#/parameters/project_name'
        - $ref: '#/parameters/camera_id'
        - $ref: '#/parameters/format'
        - $ref: '#/parameters/quality'
        - name: create
          in: query
          description: 若该流不存在，是否创建。
          required: false
          type: boolean
          default: true
      responses:
        '200':
          description: 媒体流URL
          schema:
            type: object
            required:
              - url
              - session_id
            properties:
              url:
                type: string
                description: 媒体流URL
              session_id:
                type: string
                description: 会话ID
  /{project_name}/cameras/{camera_id}/sessions/{session_id}:
    post:
      summary: 媒体流会话keepalive
      description: 客户端通过定期keepalive表明自己仍在观看该直播媒体流
      parameters:
        - $ref: '#/parameters/project_name'
        - $ref: '#/parameters/camera_id'
        - $ref: '#/parameters/session_id'
      tags: [User Session]
      responses:
        '200':
          description: keepalive成功
    delete:
      summary: 结束观看媒体流
      description: 客户端可通过该API告知结束观看媒体流。
      tags: [User Session]
      parameters:
        - $ref: '#/parameters/project_name'
        - $ref: '#/parameters/camera_id'
        - $ref: '#/parameters/session_id'
      responses:
        '200':
          description: 成功接收结束观看请求

parameters:
  project_name:
    name: project_name
    in: path
    description: 项目名称
    type: string
    required: true
  camera_id:
    name: camera_id
    in: path
    description: 摄像头ID
    type: string
    required: true
  session_id:
    name: session_id
    in: path
    description: 用户媒体流会话ID
    type: string
    required: true
  format:
    name: format
    in: query
    description: 媒体流的格式
    required: true
    type: string
    enum: ['hls', 'rtmp']
  quality:
    name: quality
    in: query
    description: 媒体流质量
    required: false
    default: ld
    type: string
    enum: ['ld', 'sd', 'hd']


definitions:
  camera:
    type: object
    required:
      - project_name
      - uuid
      - device_uuid
      - channel_index
      - flags
      - is_online
      - name
      - desc
      - longitude
      - latitude
      - altitude
    properties:
      project_name:
        type: string
        description: 摄像头所属项目名称
      uuid:
        type: string
        description: 摄像头ID
      device_uuid:
        type: string
        description: 该摄像头所属管理设备的UUID
      channel_index:
        type: integer
        description: 该摄像头在管理设备中相应的通道号
      flags:
        type: integer
        description: 各种标志位
      is_online:
        type: integer
        description: 是否在线：0离线，1在线
      name:
        type: string
        description: 名称
      desc:
        type: string
        description: 描述
      long_desc:
        type: string
        description: 长描述
      longitude:
        type: number
        format: float
        description: 经度
      latitude:
        type: number
        format: float
        description: 纬度
      altitude:
        type: number
        format: float
        description: 海拔
      ctime:
        type: string
        format: dateTime
        description: ''
      utime:
        type: string
        format: dateTime
        description: ''