swagger: '2.0'
info:
  title: IVC API
  description: IVC的REST接口
  version: 1.0.0
host: 121.41.72.231:5001
schemes:
  - http
basePath: /api/ivc/v1
produces:
  - application/json
paths:
  /cameras:
    get:
      summary: 获取摄像头列表
      tags: [Camera]
      parameters:
        - name: start
          in: query
          description: 返回的摄像头的起始索引
          required: false
          type: integer
          default: 0
        - name: limit
          in: query
          description: 最多返回的摄像头个数，最大100，最小0
          required: false
          type: integer
          default: 10
          maximum: 100
          minimum: 0
      responses:
        '200':
          description: 摄像头列表
          schema:
            type: object
            properties:
              total:
                type: integer
                required: true
                description: 摄像头总数
              start:
                type: integer
                required: true
                description: 摄像头的起始索引
              list:
                type: array
                description: 摄像头列表
                items:
                  - $ref: '#/definitions/camera'
  /cameras/{camera_id}:
    get:
      summary: 获取摄像头信息
      tags: [Camera]
      parameters:
        - $ref: '#/parameters/camera_id'
      responses:
        '200':
          description: 摄像头信息
          schema:
            $ref: '#/definitions/camera'
  /cameras/{camera_id}/streams/{format}:
    get:
      summary: 获取媒体流URL
      description:
        客户端可通过该API获取指定摄像机的指定媒体流。
      tags: [Stream]
      parameters:
        - $ref: '#/parameters/camera_id'
        - $ref: '#/parameters/format'
        - name: keepalive_required
          in: query
          description: 是否需要keepalive，若希望该媒体流一直存在，置false，若希望该媒体流在没有人观看后自动关闭，置true。
          required: false
          type: boolean
          default: false
        - name: create
          in: query
          description: 若该流不存在，是否创建。
          required: false
          type: boolean
          default: true
      responses:
        '200':
          description: 媒体流URL
          schema:
            type: object
            properties:
              url:
                type: string
                required: true
                description: 媒体流URL
    delete:
      summary: 关闭媒体流
      description: 客户端可通过该API关闭必定媒体流。
      tags:
        - Stream
      parameters:
        - $ref: '#/parameters/camera_id'
        - $ref: '#/parameters/format'
        - name: force
          in: query
          description: 是否强行关闭该媒体流，当为true时，无论是否有人观看，均关闭该流；为false时，若有人观看，则等观看结束后再关闭该媒体流。
          type: boolean
          required: false
          default: false
      responses:
        '200':
          description: 成功接收删除命令
  /cameras/{camera_id}/streams/{format}/keepalive:
    post:
      summary: 客户端keepalive
      description: 客户端通过定期keepalive表明自己仍在观看该媒体流
      parameters:
        - $ref: '#/parameters/camera_id'
        - $ref: '#/parameters/format'
      tags: [Stream]
      responses:
        '200':
          description: keepalive成功

parameters:
  camera_id:
    name: camera_id
    in: path
    description: 摄像头ID
    type: string
    required: true
  format:
    name: format
    in: path
    description: 媒体流的格式
    required: true
    type: string
    enum: ['hls', 'rtmp']

definitions:
  stream:
    type: object
    properties:
      format:
        type: string
        required: true
        description: 媒体流的格式
  camera:
    type: object
    properties:
      id:
        type: string
        required: true
        description: 摄像头ID
      location:
        type: string
        required: false
        description: 摄像头位置信息
      desc:
        type: string
        required: false
        description: 摄像头的文字描述
      streams:
        type: array
        items:
          - $ref: '#/definitions/stream'

