"""add access_key table

Revision ID: 4fefeee0f1d0
Revises: f3d4f4ba508
Create Date: 2016-01-12 00:51:15.238576

"""

# revision identifiers, used by Alembic.
revision = '4fefeee0f1d0'
down_revision = 'f3d4f4ba508'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_key',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('key_id', sa.String(length=32, convert_unicode=True), nullable=False),
    sa.Column('secret', sa.String(length=64, convert_unicode=True), server_default=u'', nullable=False),
    sa.Column('desc', sa.String(length=255, convert_unicode=True), server_default=u'', nullable=False),
    sa.Column('username', sa.String(length=64, convert_unicode=True), server_default=u'', nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text(u'0'), nullable=False),
    sa.Column('key_type', sa.SmallInteger(), server_default=sa.text(u'0'), nullable=False),
    sa.Column('ctime', sa.TIMESTAMP(), server_default=sa.text(u'0'), nullable=False),
    sa.ForeignKeyConstraint(['username'], [u'user.username'], onupdate=u'CASCADE', ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_key_key_id'), 'access_key', ['key_id'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_access_key_key_id'), table_name='access_key')
    op.drop_table('access_key')
    ### end Alembic commands ###
